# On utilise une image plus complète, avec les outils de build pré-installés
FROM python:3.12

# Installation des dépendances système nécessaires à la compilation (Rust, GCC, libpq)
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    libpq-dev \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
    && rm -rf /var/lib/apt/lists/*

# Ajout de cargo (Rust) au PATH
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
